apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: spark-pi-prometheus-driver
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: spark-pi-prometheus
  podMetricsEndpoints:
  - port: "8090"
